version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  # NuGet dependencies for main project
  - package-ecosystem: "nuget"
    directory: "/src/RVToolsMerge/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps"

  # NuGet dependencies for solution-level packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
