allowlist:
  domains:
    - "cdn.fwupd.org"
    - "crl3.digicert.com"
    - "crl4.digicert.com"
    - "ocsp.digicert.com"
    - "s.symcb.com"
    - "s.symcd.com"
    - "ts-crl.ws.symantec.com"
    - "ts-ocsp.ws.symantec.com"
    - "www.microsoft.com"
    - "aka.ms"
    - "download.visualstudio.microsoft.com"
    - "nuget.org"
    - "api.nuget.org"
    - "packages.nuget.org"
    - "dist.nuget.org"