name: Generate SBOM

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Install CycloneDX
        run: dotnet tool install --global CycloneDX
      
      - name: Generate SBOM
        run: |
          dotnet CycloneDX RVToolsMerge.csproj -o . -j
          mv bom.json RVToolsMerge-sbom.json
      
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: RVToolsMerge-SBOM
          path: RVToolsMerge-sbom.json
      
      - name: Attach SBOM to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: RVToolsMerge-sbom.json
          token: ${{ secrets.GITHUB_TOKEN }}
